"""Formal consolidated version of the SeqSimFit sequence simulator."""

from .simulator import (
    EvaluationResult,
    ProposalRecord,
    SequenceSimulator,
    SimulationResult,
    seq_simulator,
)
from .scorers import ScorerConfig
from .analysis import (
    AA_ALPHABET,
    CorrelationResult,
    KLDivergenceResult,
    MutationEvent,
    PositionFrequencyProfile,
    SubstitutionModel,
    TrajectoryAnalysis,
    aggregate_site_substitution_counts,
    alignment_kl_divergence,
    amino_acid_composition,
    analyze_simulator,
    analyze_trajectory,
    compare_exchangeability,
    correlate_site_rates,
    estimate_substitution_model,
    first_state_at_identity,
    hamming_distance,
    identity_trajectory,
    mutation_events,
    position_frequencies,
    read_fasta,
    remove_consecutive_duplicates,
    sequence_identity,
    site_residue_diversity,
    site_substitution_counts,
    trim_alignment_to_query,
    write_fasta,
)

__all__ = [
    "AA_ALPHABET",
    "CorrelationResult",
    "EvaluationResult",
    "KLDivergenceResult",
    "MutationEvent",
    "PositionFrequencyProfile",
    "ProposalRecord",
    "ScorerConfig",
    "SequenceSimulator",
    "SimulationResult",
    "SubstitutionModel",
    "TrajectoryAnalysis",
    "aggregate_site_substitution_counts",
    "alignment_kl_divergence",
    "amino_acid_composition",
    "analyze_simulator",
    "analyze_trajectory",
    "compare_exchangeability",
    "correlate_site_rates",
    "estimate_substitution_model",
    "first_state_at_identity",
    "hamming_distance",
    "identity_trajectory",
    "mutation_events",
    "position_frequencies",
    "read_fasta",
    "remove_consecutive_duplicates",
    "sequence_identity",
    "seq_simulator",
    "site_residue_diversity",
    "site_substitution_counts",
    "trim_alignment_to_query",
    "write_fasta",
]
